package tieto.bank;

import tieto.bank.admin.*;
import tieto.bank.state.*;

import com.vaadin.annotations.*;
import com.vaadin.ui.*;

public class AccountDetailForm extends CustomComponent {

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Button btnSave;
	@AutoGenerated
	private Button btnRemove;
	@AutoGenerated
	private TextField txtAccBalance;
	@AutoGenerated
	private Label lblAccBalance;

	StateHolder stateholder;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public AccountDetailForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		this.stateholder = new StateHolder(this, new EmptyState());
	}

	Account account;

	public void setAccount(Account account) {
		if (account != null) {
			this.account = account;
			if (AccountType.Private.equals(account.getType()))
				this.stateholder.setState(new PrivateState());
			else if (AccountType.Corporate.equals(account.getType()))
				this.stateholder.setState(new CorporateState());
		}
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setColumns(2);
		mainLayout.setRows(2);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// lblAccBalance
		lblAccBalance = new Label();
		lblAccBalance.setImmediate(false);
		lblAccBalance.setWidth("-1px");
		lblAccBalance.setHeight("-1px");
		lblAccBalance.setValue("Account balance : ");
		mainLayout.addComponent(lblAccBalance, 0, 0);
		mainLayout.setComponentAlignment(lblAccBalance, new Alignment(48));

		// txtAccBalance
		txtAccBalance = new TextField();
		txtAccBalance.setImmediate(false);
		txtAccBalance.setWidth("-1px");
		txtAccBalance.setHeight("-1px");
		txtAccBalance.setSecret(false);
		mainLayout.addComponent(txtAccBalance, 1, 0);
		mainLayout.setComponentAlignment(txtAccBalance, new Alignment(48));

		// btnRemove
		btnRemove = new Button();
		btnRemove.setCaption("Remove");
		btnRemove.setImmediate(true);
		btnRemove.setWidth("-1px");
		btnRemove.setHeight("-1px");
		mainLayout.addComponent(btnRemove, 0, 1);
		mainLayout.setComponentAlignment(btnRemove, new Alignment(48));

		// btnSave
		btnSave = new Button();
		btnSave.setCaption("Save");
		btnSave.setImmediate(true);
		btnSave.setWidth("-1px");
		btnSave.setHeight("-1px");
		mainLayout.addComponent(btnSave, 1, 1);
		mainLayout.setComponentAlignment(btnSave, new Alignment(48));

		return mainLayout;
	}

}
